hmcts/azure-shutter-pages

CODEOWNERS
README.md
azure-pipelines.yml

[AB#700](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/700)

Pipeline + docs

---

azure-pipelines.yml

[AB#700](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/700)
```
[ ] Yes
[ ] No
```

Add prod shutter content

---

azure-pipelines.yml

https://tools.hmcts.net/jira/browse/RPE-1187
```
[ ] Yes
[x] No
```

Add cmc shutter pages

---

azure-pipelines.yml

ccd shutter page

---

azure-pipelines.yml

Add default shutter for xui

---

iaaip/index.html

https://tools.hmcts.net/jira/browse/RIA-3151
Copy changes for shutter page as service has been paused
```
[ ] Yes
[ X ] No
```

RIA-3151: Changes to shutter pages as service has been paused

---

pcq/index.html

https://tools.hmcts.net/jira/browse/PCQ-400

PCQ-400: Add probate caveats link

---

pcq/index.html

Add CMC links to PCQ shutter page.
```
[ ] Yes
[x] No
```

Add CMC links to PCQ shutter

---

pcq/index.html

Add divorce links to PCQ shutter
```
[ ] Yes
[x] No
```

Add divorce links

---

azure-pipelines.yml

Fact shutter Update azure-pipelines.yml

---

pcq/index.html

Add SSCS link to PCQ shutter page
```
[ ] Yes
[x] No
```

PCQ: Add SSCS link

---

azure-pipelines.yml

NFDIV shutter Update azure-pipelines.yml

---

sscstrib/index.html

SSCS-8438: SYA – Shutter page – Contact us

---

sscscor/index.html

SSCS-8439: MYA – Shutter page – Contact us and text

---

cmc/index.html
cmclegal/index.html

ROC-9303 | Update Shuttering Content & Contact detail for OCMC/Legal Rep
-- | --
```
[ ] Yes
[x] No
```

updated cmc content

---

azure-pipelines.yml

- Adding task for toffee sbox shutter
- Updating subscription for toffee
- Updating toffee sub name

Updating toffee sub name

---

azure-pipelines.yml

- Added JD bureau and public shutter pages
```
[ ] Yes
[x] No
```

DTSPO-4365 - add jd bureau and jd public shutter pages

---

azure-pipelines.yml

- Refactor pipeline
- Add juror apps
```
[ ] Yes
[x] No
```

DTSPO-4365

---

azure-pipelines.yml

Fix Jd public storage account name

---

azure-pipelines.yml

fix jd public name for real this time

---

pcq/index.html

https://tools.hmcts.net/jira/browse/PCQ-1234
Add IAC to shutter page
```
[ ] Yes
[x] No
```

PCQ-1234 Add IAC link

---

azure-pipelines.yml

Add PIP to the shutter
```
[ ] Yes
[ X ] No
```

Add PIP Shutter

---

azure-pipelines.yml

https://tools.hmcts.net/jira/browse/FACT-1142
Add rpts to azure-pipelines.yml
```
[ ] Yes
[x ] No
```

Add rpts to azure-pipelines.yml

---

azure-pipelines.yml

Default shutter page config updated for adoption service.
```
[ ] Yes
[x] No
```

Adoption shutter page testing with default page.

---

pcq/index.html

Add adoption link to PCQ shutter
```
[ ] Yes
[x] No
```

Add adoption link to PCQ shutter

---

pcq/index.html

https://tools.hmcts.net/jira/browse/PCQ-1539
Add make a plea link
```
[ ] Yes
[x] No
```

PCQ-1539: Add Make a Plea link

---

pcq/index.html

https://tools.hmcts.net/jira/browse/PCQ-1591
Add employment tribunal link to azure shutter page
```
[ ] Yes
[x] No
```

Update azure shutter page with employment tribunal link

---

pcq/index.html

https://tools.hmcts.net/jira/browse/PCQ-1589
Add Juror Digital link to shutter page
```
[ ] Yes
[x] No
```

Adding Juror Digital URL to Shutter Page

---

azure-pipelines.yml

Updating private law shutter name

---

privatel/index.html

Private law shuttering content update

---

azure-pipelines.yml

https://tools.hmcts.net/jira/browse/SNI-4080
Amend Special Tribunals custom shutter pipeline name to match storage account name.
```
[ ] Yes
[x] No
```

Amend Special Tribunals custom shutter pipeline name

---

azure-pipelines.yml

https://tools.hmcts.net/jira/browse/S28-1521
prerequesite config: https://github.com/hmcts/sds-azure-platform/blob/master/environments/prod/prod.tfvars#L1015
**Does this PR introduce a breaking change?**
```
[ ] Yes
[x] No
```

S28-1521 Add a default shutter page to PRE portal

---

.github/workflows/default.yaml

Github action to deploy static Webapp config

---

.github/workflows/default.yaml

Update git branch in default.yaml

---

.github/workflows/plum-sbox.yaml
.github/workflows/plum.yaml
.github/workflows/toffee-sbox.yaml
.github/workflows/toffee.yaml
README.md
pipeline_template.yaml

Update config to create an app per environment

---

.github/workflows/deploy-shutter-pages.yaml
.github/workflows/toffee.yaml
README.md
pipeline_template.yaml

create a reusable workflow

---

.github/workflows/court-tribunal-hearings.yaml
.github/workflows/pip-frontend.yaml
.github/workflows/plum.yaml
.github/workflows/toffee.yaml
.github/workflows/vh-admin-web.yaml
.github/workflows/vh-video-web.yaml
pipeline_template.yaml

Push default pages to app(s) in sds

---

.github/workflows/et-pet.yaml
.github/workflows/et-staff-pet.yaml
.github/workflows/hwf-pet.yaml
.github/workflows/hwf-staff-pet.yaml
.github/workflows/tt-pet.yaml

Cakeben patch 1

---

hwf-pet/index.html

Add a line for when hwf will be back up

---

et-sya/index.html

https://tools.hmcts.net/jira/browse/RET-4540
Updating text on shutter page

Updating shutter page message

---

pcq/index.html

https://tools.hmcts.net/jira/browse/PCQ-1519
Add special tribunal link to pcq shutter page

Add special tribunal link to shutter page on production

---

adoption/index.html

https://tools.hmcts.net/jira/browse/FPET-606
Adoption- CUI & LA Shutter page implementation - Must have for public beta release

FPET-606-updated Adoption shutter page for private beta

---

pcq/index.html

https://tools.hmcts.net/jira/browse/FPET-606
Adoption- CUI & LA Shutter page implementation - Must have for public beta release

FPET-606-updated adoption public release DNS in redirect url

---

adoption/index.html

https://tools.hmcts.net/jira/browse/FPET-606
Adoption- CUI & LA Shutter page implementation - Must have for public beta release

FPET-606-updated redirect URL to eligibility start page

---

et-sya/index.html

Update shutter page for DB Migration

Update ET Shutter page

---

et-sya/index.html

Update the shutter page date time for CCD release

ET - Shutter page update

---

et-sya/index.html

Update shutter message

---

.github/workflows/juror-bureau.yaml
.github/workflows/juror-public.yaml
.github/workflows/juror.yaml

juror: add public and juror apps

---

et-sya/index.html

ET Update shutter message

---

portal/index.html

Update PRE shutter page content

---

juror-legacy/index.html

update to match email

---

probate/caveats/index.html

DTSPB-3958: Shuttering Page Caveats Fix

---

juror-legacy/index.html
juror-public/index.html
juror/index.html

update to agreed wording for go-live

---

.github/workflows/sscs-ibca.yaml

https://tools.hmcts.net/jira/browse/DTSPO-22714
Creating missing shutter app for the appeal-infected-blood-compensation-decision.service.gov.uk

Added missing static app for sscs ibca application

---

.github/workflows/portal.yaml

For some reason, the static app hasn't been deployed correctly. fixing it with this PR

Deploying portal static app which isn't seem to be deployed

---

.github/workflows/tools-atlassian-prp.yaml
.github/workflows/tools-atlassian-staging.yaml

https://tools.hmcts.net/jira/browse/DTSPO-23473
Added shutter app pages for the Staging and PRP atlassian apps.

DTSPO-23473 - added shutter app contents

---

.github/workflows/default.yaml
scripts/find-empty-static-app.sh

https://tools.hmcts.net/jira/browse/DTSPO-22779
Adding default workflow which will look all the static Apps and then if any of them does not have pages uploaded, it will upload default pages.  The workflow will run every hour.

DTSPO-22779 - run tests to see if this going to work

---

.github/workflows/default.yaml

Fixing issue with this workflow to pass the values from one job to another job

DTSPO-22779 - fixing issue with this workflow

---

.github/workflows/default.yaml
README.md

https://tools.hmcts.net/jira/browse/DTSPO-22779
Added read me for the default page changes
Added IF condition so that it will not run upload process for default toffee app
Tested with couple of Static Web apps e.g. plumclassic  and test-static-app

Dtspo 22779 readme

---

et-sya/index.html
et-syr/index.html

Update ET Shutter message as service is time sensitive

ET - Update shutter message
